# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('reddit_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('downs', models.PositiveIntegerField()),
                ('created_utc', models.BigIntegerField()),
                ('body', models.TextField()),
                ('body_html', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedditUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('num_requests', models.IntegerField(default=0)),
                ('last_requested', models.DateTimeField(default=datetime.datetime(2017, 6, 8, 9, 47, 58, 181000, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('reddit_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('is_self', models.BooleanField()),
                ('score', models.IntegerField()),
                ('num_comments', models.PositiveIntegerField()),
                ('created_utc', models.BigIntegerField()),
                ('author', models.CharField(max_length=50)),
                ('subreddit', models.CharField(max_length=100)),
                ('permalink', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=500)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reddit.RedditUser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reddit.Thread'),
        ),
    ]
