# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reddituser',
            name='last_requested',
        ),
        migrations.RemoveField(
            model_name='reddituser',
            name='num_requests',
        ),
        migrations.AddField(
            model_name='reddituser',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reddituser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
