# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 11:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20170615_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='followers',
            field=models.ManyToManyField(related_name='reddit_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
