version: "3"

services:
  database:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 25432:5432

  web:
    image: links:latest
    command: ./manage.py runserver 0.0.0.0:8000
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../app:/app
    links:
      - database
    environment:
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: database
      PGPORT: 5432
      DJANGO_SETTINGS_MODULE: links.settings.dev

volumes:
  postgres-data:
