# Generated by Django 3.0.8 on 2020-07-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200712_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='reddit_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
