# Generated by Django 3.0.8 on 2020-07-18 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_link_reddit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='reddit_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
